/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-01-11 11:30:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chengtao.entity.TabType;
import com.chengtao.entity.Demand;
import com.chengtao.entity.Supply;
import com.chengtao.entity.Exhibition;
import com.chengtao.entity.News;
import java.util.ArrayList;
import com.chengtao.entity.UserType;
import com.chengtao.entity.CompanyUser;
import com.chengtao.entity.PersonUser;
import com.chengtao.utils.ParamUtils;

public final class activity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.chengtao.entity.PersonUser");
    _jspx_imports_classes.add("com.chengtao.entity.UserType");
    _jspx_imports_classes.add("com.chengtao.utils.ParamUtils");
    _jspx_imports_classes.add("com.chengtao.entity.News");
    _jspx_imports_classes.add("com.chengtao.entity.Demand");
    _jspx_imports_classes.add("com.chengtao.entity.Supply");
    _jspx_imports_classes.add("com.chengtao.entity.Exhibition");
    _jspx_imports_classes.add("com.chengtao.entity.TabType");
    _jspx_imports_classes.add("com.chengtao.entity.CompanyUser");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

   		Object user = request.getAttribute(ParamUtils.ENTITY_USER);
   		PersonUser personUser = null;
   		CompanyUser companyUser = null;
   		UserType type = UserType.Visitor;
   		if(user instanceof PersonUser){
   			personUser = (PersonUser)user;
   			if(personUser != null){
   				type = UserType.PersonUser;
   			}
   		}else{
   			companyUser = (CompanyUser)user;
   			if(companyUser != null){
   				type = UserType.CompanyUser;
   			}
   		}
   		ArrayList<News> news = new ArrayList<>();
   		ArrayList<Exhibition> exhibitions = new ArrayList<>();
   		ArrayList<Supply> supplies = new ArrayList<>();
   		ArrayList<Demand> demands = new ArrayList<>();
   		TabType tab = TabType.NEWS;
   		int currentPage = 1;
   		Object n = request.getAttribute(ParamUtils.ENTITY_NEWS);
   		Object e = request.getAttribute(ParamUtils.ENTITY_EXHIBITON);
   		Object s = request.getAttribute(ParamUtils.ENTITY_SUPPLY);
   		Object d = request.getAttribute(ParamUtils.ENTITY_DEMAND);
   		Object t = request.getAttribute(ParamUtils.ENTITY_TAB);
   		Object cp = request.getAttribute(ParamUtils.ENTITY_PAGE);
   		if(n != null){
   			news = (ArrayList<News>)n;
   		}
   		if(e != null){
   			exhibitions = (ArrayList<Exhibition>)e;
   		}
   		if(s != null){
   			supplies = (ArrayList<Supply>)s;
   		}
   		if(d != null){
   			demands = (ArrayList<Demand>)d;
   		}
   		if(t != null){
   			tab = (TabType)t;
   		}
   		if(cp != null){
   			currentPage = (int)cp;
   		}
   		
   
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/bootstrap.min.js\"></script>\r\n");
      out.write("<title>文化创意</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("\">文化创意</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t        <li class=\"dropdown\">\r\n");
      out.write("\t\t          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">管理<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t          \t");
if(type != UserType.Visitor){
      out.write("\r\n");
      out.write("\t\t          \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_USER_INFO);
      out.write("\">个人信息</a></li>\r\n");
      out.write("\t\t          \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_USER_LOGOUT);
      out.write("\">注销</a></li>\r\n");
      out.write("\t\t          \t");
}
      out.write("\r\n");
      out.write("\t\t          \t");
if(type == UserType.Visitor){ 
      out.write("\r\n");
      out.write("\t\t            \t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.VIEW_LOGIN);
      out.write("\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t        </li>\r\n");
      out.write("\t\t      </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"container user-main\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 user-left\">\r\n");
      out.write("\t\t\t\t");

				switch(type){
				case Visitor:
					out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
					break;
				case PersonUser:
					if(personUser != null){
						if(personUser.getAvatar() != null){
							out.println("<img src=\""+personUser.getAvatar() +"\""+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				case CompanyUser:
					if(companyUser != null){
						if(companyUser.getAvatar() != null){
							out.println("<img src=\""+companyUser.getAvatar()+"\""+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"name\">\r\n");
      out.write("\t\t\t\t");

				switch(type){
					case Visitor:
						out.println("游客");
						out.println("<p class=\"text-muted\">我只是一个游客而已</p>");
						break;
					case PersonUser:
						if(personUser != null){
							out.println(personUser.getName());
							if(personUser.getIntroduce() != null){
								out.println("<p class=\"text-muted\">"+personUser.getIntroduce()+"</p>");
							}
						}
						break;
					case CompanyUser:
						if(companyUser != null){
							out.println(companyUser.getName());
							if(companyUser.getIntroduce() != null){
								out.println("<p class=\"text-muted\">"+companyUser.getIntroduce()+"</p>");
							}
						}
						break;
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t");

					switch(type){
						case PersonUser:
							if(personUser != null){
								if(personUser.getEmail() != null){
									out.print("<p><span>邮箱:</span>"+personUser.getEmail()+"</p>");
								}
								if(personUser.getTel() != null){
									out.print("<p><span>电话:</span></span>"+personUser.getTel()+"</p>");
								}
								if(personUser.getAddress() != null){
									out.print("<p><span>地址:</span>"+personUser.getAddress()+"</p>");
								}
							}
							break;
						case CompanyUser:
							if(companyUser != null){
								if(companyUser.getEmail() != null){
									out.print("<p><span>邮箱:</span>"+companyUser.getEmail()+"</p>");
								}
								if(companyUser.getTel() != null){
									out.print("<p><span>电话:</span></span>"+companyUser.getTel()+"</p>");
								}
								if(companyUser.getAddress() != null){
									out.print("<p><span>地址:</span>"+companyUser.getAddress()+"</p>");
								}
							}
							break;
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-9 user-right\">\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t  <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(ParamUtils.TAB_NEWS);
      out.write("\">所有资讯</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(ParamUtils.TAB_EXHIBITON);
      out.write("\">所有展会</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(ParamUtils.TAB_SUPPLY);
      out.write("\">所有供应</a></li>\r\n");
      out.write("\t\t\t\t  <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(ParamUtils.TAB_DEMAND);
      out.write("\">所有需求</a></li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled list\">\r\n");
      out.write("\t\t\t\t\t");

					String mTab = "";
					int total = 0;
					switch(tab){
						case NEWS:
							mTab = ParamUtils.TAB_NEWS;
							if(news != null && news.size() > 0){
								total = news.get(0).getTotal();
								for(News news2 : news){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <h4 class=\"media-heading\"><a href=\"#\" class=\"lead\">");
      out.print(news2.getTitle());
      out.write("</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布企业:");
      out.print(news2.getCompanyName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布时间:");
      out.print(news2.getUpdateAt() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>访问数量:");
      out.print(news2.getVisit() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
							}
							break;
						case EXHIBITON:
							mTab = ParamUtils.TAB_EXHIBITON;
							if(exhibitions != null && exhibitions.size() > 0){
								total = exhibitions.get(0).getTotal();
								for(Exhibition ex : exhibitions){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <h4 class=\"media-heading\"><a href=\"#\" class=\"lead\">");
      out.print(ex.getTheme());
      out.write("</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布企业:");
      out.print(ex.getCompanyName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布时间:");
      out.print(ex.getUpdateAt() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>访问数量:");
      out.print(ex.getVisit() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
							}
							break;
						case SUPPLY:
							mTab = ParamUtils.TAB_SUPPLY;
							if(supplies != null && supplies.size() > 0){
								for(Supply su : supplies){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <h4 class=\"media-heading\"><a href=\"#\" class=\"lead\">");
      out.print( su.getName() );
      out.write("</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布人:");
      out.print(su.getCompanyName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布时间:");
      out.print(su.getUpdateAt() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>访问数量:");
      out.print(su.getVisit() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
							}
							break;
						case DEMAND:
							mTab = ParamUtils.TAB_DEMAND;
							if(demands != null && demands.size() > 0){
								for(Demand de : demands){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <h4 class=\"media-heading\"><a href=\"#\" class=\"lead\">");
      out.print(de.getName());
      out.write("</a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布人:");
      out.print(de.getUserName() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>发布时间:");
      out.print(de.getUpdateAt() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <p>访问数量:");
      out.print(de.getVisit() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
}
							}
							break;
					}
					
					
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t<nav style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t");

					int lastPage = total / ParamUtils.PAGE_SIZE;;
					if(total % ParamUtils.PAGE_SIZE != 0){
						lastPage++;
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t  <ul class=\"pagination bottom-nav\" >\r\n");
      out.write("\t\t\t\t  \t");

			  		if(currentPage == 1){
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t <li class=\"disabled\"><span>首页</span></li>\r\n");
      out.write("\t\t\t  \t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(mTab);
      out.write('&');
      out.print(ParamUtils.PAGE);
      out.write("=1\">首页</a></li>\r\n");
      out.write("\t\t\t\t  \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t  \t");

				  	for(int i = currentPage - 1; i >= currentPage - 2; i--){
				  		if(i >= 1){
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(mTab);
      out.write('&');
      out.print(ParamUtils.PAGE);
      out.write('=');
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t  \t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t  \t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t    <li class=\"active\"><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(mTab);
      out.write('&');
      out.print(ParamUtils.PAGE);
      out.write('=');
      out.print(currentPage);
      out.write('"');
      out.write('>');
      out.print(currentPage );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t    ");

				  	for(int i = currentPage + 1; i <= currentPage + 2; i++){
					  	if(i <= lastPage){
      out.write("\r\n");
      out.write("\t\t\t\t\t  \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(mTab);
      out.write('&');
      out.print(ParamUtils.PAGE);
      out.write('=');
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t  \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t  \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t  \t");

			  		if(lastPage <= 1 || lastPage == currentPage){
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t <li class=\"disabled\"><span>尾页</span></li>\r\n");
      out.write("\t\t\t  \t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t  \t\t <li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_ACTIVITY);
      out.write('?');
      out.print(ParamUtils.TAB);
      out.write('=');
      out.print(mTab);
      out.write('&');
      out.print(ParamUtils.PAGE);
      out.write('=');
      out.print(lastPage);
      out.write("\">尾页</a></li>\r\n");
      out.write("\t\t\t\t  \t");
}
      out.write("\r\n");
      out.write("\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t</nav>\t    \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
