/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-01-10 04:31:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chengtao.entity.UserType;
import com.chengtao.entity.CompanyUser;
import com.chengtao.entity.PersonUser;
import com.chengtao.utils.ParamUtils;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.chengtao.entity.PersonUser");
    _jspx_imports_classes.add("com.chengtao.entity.UserType");
    _jspx_imports_classes.add("com.chengtao.utils.ParamUtils");
    _jspx_imports_classes.add("com.chengtao.entity.CompanyUser");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

   		Object user = request.getAttribute(ParamUtils.ENTITY_USER);
   		PersonUser personUser = null;
   		CompanyUser companyUser = null;
   		UserType type = UserType.Visitor;
   		if(user instanceof PersonUser){
   			personUser = (PersonUser)user;
   			if(personUser != null){
   				type = UserType.PersonUser;
   			}
   		}else{
   			companyUser = (CompanyUser)user;
   			if(companyUser != null){
   				type = UserType.CompanyUser;
   			}
   		}
   
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/bootstrap.min.js\"></script>\r\n");
      out.write("<title>文化创意</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">文化创意</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t        <li class=\"dropdown\">\r\n");
      out.write("\t\t          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">管理<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t          \t");
if(type != UserType.Visitor){
      out.write("\r\n");
      out.write("\t\t          \t\t<li><a href=\"#\">个人信息</a></li>\r\n");
      out.write("\t\t          \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/user/logout\">注销</a></li>\r\n");
      out.write("\t\t          \t");
}
      out.write("\r\n");
      out.write("\t\t          \t");
if(type == UserType.Visitor){ 
      out.write("\r\n");
      out.write("\t\t            \t<li><a href=\"");
      out.print(request.getContextPath());
      out.write('/');
      out.print(ParamUtils.VIEW_LOGIN);
      out.write("\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t        </li>\r\n");
      out.write("\t\t      </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"container user-main\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3 user-left\">\r\n");
      out.write("\t\t\t\t");

				switch(type){
				case Visitor:
					out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
					break;
				case PersonUser:
					if(personUser != null){
						if(personUser.getAvatar() != null){
							out.println("<img src=\""+personUser.getAvatar()+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				case CompanyUser:
					if(companyUser != null){
						if(companyUser.getAvatar() != null){
							out.println("<img src=\""+companyUser.getAvatar()+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"name\">\r\n");
      out.write("\t\t\t\t");

				switch(type){
					case Visitor:
						out.println("游客");
						out.println("<p class=\"text-muted\">我只是一个游客而已</p>");
						break;
					case PersonUser:
						if(personUser != null){
							out.println(personUser.getName());
							if(personUser.getIntroduce() != null){
								out.println("<p class=\"text-muted\">"+personUser.getIntroduce()+"</p>");
							}
						}
						break;
					case CompanyUser:
						if(companyUser != null){
							out.println(companyUser.getName());
							if(companyUser.getIntroduce() != null){
								out.println("<p class=\"text-muted\">"+companyUser.getIntroduce()+"</p>");
							}
						}
						break;
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<hr/>\r\n");
      out.write("\t\t\t\t");

					switch(type){
						case PersonUser:
							if(personUser != null){
								if(personUser.getEmail() != null){
									out.print("<p><span>邮箱:</span>"+personUser.getEmail()+"</p>");
								}
								if(personUser.getTel() != null){
									out.print("<p><span>电话:</span></span>"+personUser.getTel()+"</p>");
								}
								if(personUser.getAddress() != null){
									out.print("<p><span>地址:</span>"+personUser.getAddress()+"</p>");
								}
							}
							break;
						case CompanyUser:
							if(companyUser != null){
								if(companyUser.getEmail() != null){
									out.print("<p><span>邮箱:</span>"+companyUser.getEmail()+"</p>");
								}
								if(companyUser.getTel() != null){
									out.print("<p><span>电话:</span></span>"+companyUser.getTel()+"</p>");
								}
								if(companyUser.getAddress() != null){
									out.print("<p><span>地址:</span>"+companyUser.getAddress()+"</p>");
								}
							}
							break;
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-9 user-left\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs nav-justified\" role=\"tablist\" id=\"culture-tab\">\r\n");
      out.write("\t\t\t\t  <li id=\"news-tab\" role=\"presentation\" class=\"active\"><a href=\"#news\">所有资讯</a></li>\r\n");
      out.write("\t\t\t\t  <li id=\"exhibition-tab\" role=\"presentation\"><a href=\"#exhibition\">所有展会</a></li>\r\n");
      out.write("\t\t\t\t  <li id=\"supply-tab\" role=\"presentation\"><a href=\"#supply\">所有供应</a></li>\r\n");
      out.write("\t\t\t\t  <li id=\"demand-tab\" role=\"presentation\"><a href=\"#demand\">所有需求</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div id=\"culture-tab-content\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"news\" aria-labelledby=\"news-tab\">\r\n");
      out.write("\t\t\t\t        <p>所有资讯</p>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"exhibition\" aria-labelledby=\"exhibition-tab\">\r\n");
      out.write("\t\t\t\t        <p>所有展会</p>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"supply\" aria-labelledby=\"supply-tab\">\r\n");
      out.write("\t\t\t\t        <p>所有供应</p>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"demand\" aria-labelledby=\"demand-tab\">\r\n");
      out.write("\t\t\t\t        <p>所有需求</p>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
