/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-01-10 12:53:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chengtao.entity.WebTip;
import com.chengtao.entity.UserType;
import com.chengtao.entity.CompanyUser;
import com.chengtao.entity.PersonUser;
import com.chengtao.utils.ParamUtils;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.chengtao.entity.PersonUser");
    _jspx_imports_classes.add("com.chengtao.entity.UserType");
    _jspx_imports_classes.add("com.chengtao.utils.ParamUtils");
    _jspx_imports_classes.add("com.chengtao.entity.WebTip");
    _jspx_imports_classes.add("com.chengtao.entity.CompanyUser");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Object user = request.getAttribute(ParamUtils.ENTITY_USER);
	PersonUser personUser = null;
	CompanyUser companyUser = null;
	UserType type = UserType.Visitor;
	if(user != null){
		if(user instanceof PersonUser){
			personUser = (PersonUser)user;
			if(personUser != null){
				type = UserType.PersonUser;
			}
		}else{
			companyUser = (CompanyUser)user;
			if(companyUser != null){
				type = UserType.CompanyUser;
			}
		}
	}
	Object tipObject = request.getAttribute(ParamUtils.ENTITY_WEB_TIP);
	WebTip tip = null;
	if(tipObject != null){
		tip = (WebTip)tipObject;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/jquery.validate.min.js\"></script>\r\n");
      out.write("<title>文化创意</title>\r\n");
      out.write("</head>\r\n");

if(tip != null){
	out.println(tip.toString());
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath());
      out.write("\">文化创意</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t        <li class=\"dropdown\">\r\n");
      out.write("\t\t          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">管理<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t          <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t          \t");
if(type != UserType.Visitor){
      out.write("\r\n");
      out.write("\t\t          \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_USER_INFO);
      out.write("\">个人信息</a></li>\r\n");
      out.write("\t\t          \t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.SERVLET_USER_LOGOUT);
      out.write("\">注销</a></li>\r\n");
      out.write("\t\t          \t");
}
      out.write("\r\n");
      out.write("\t\t          \t");
if(type == UserType.Visitor){ 
      out.write("\r\n");
      out.write("\t\t            \t<li><a href=\"");
      out.print(request.getContextPath());
      out.print(ParamUtils.VIEW_LOGIN);
      out.write("\">登录</a></li>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t          </ul>\r\n");
      out.write("\t\t        </li>\r\n");
      out.write("\t\t      </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"container user-main\">\r\n");
      out.write("\t\t<h3>个人信息</h3>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t  \t");

			  		int id = 0;
			  		if(type == UserType.PersonUser){
			  			id = personUser.getId();
			  		}else if(type == UserType.CompanyUser){
			  			id = companyUser.getId();
			  		}
			  	
      out.write("\r\n");
      out.write("\t\t\t  \t");

			  		int mTpye = -1;
			  		if(type == UserType.PersonUser){
			  			mTpye = 0;
			  		}else if(type == UserType.CompanyUser){
			  			mTpye = 1;
			  		}
			  	
      out.write("\r\n");
      out.write("\t\t\t  \t");

					String userModifyPath = request.getContextPath() + ParamUtils.SERVLET_USER_MODIFY; 
			  		userModifyPath += "?" + ParamUtils.FOREM_USER_ID + "=" + id + "&";
			  		userModifyPath += ParamUtils.FOREM_USER_TYPE + "=" + mTpye;
				
      out.write("\r\n");
      out.write("\t\t\t\t<form role=\"form\" id=\"user-form\" method=\"POST\" action=\"");
      out.print(userModifyPath);
      out.write("\">\r\n");
      out.write("\t\t\t\t  ");

				  	String name = "";
				  	if(type == UserType.PersonUser){
			  			name = personUser.getName();
			  		}else if(type == UserType.CompanyUser){
			  			name = companyUser.getName();
			  		}
				  	if(name == null){
		  				name = "";
		  			}
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>用户名</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(name);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_NAME );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_NAME );
      out.write("\" placeholder=\"请输入用户名\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\" id=\"form-p\">\r\n");
      out.write("\t\t\t\t    <label>密码</label>\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\"id=\"");
      out.print(ParamUtils.FOREM_USER_PASSWORD );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_PASSWORD );
      out.write("\" placeholder=\"请输入密码\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\" id=\"form-p-again\">\r\n");
      out.write("\t\t\t\t    <label>确认密码</label>\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\"id=\"");
      out.print(ParamUtils.FOREM_USER_PASSWORD_AGAIN );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_PASSWORD_AGAIN );
      out.write("\" placeholder=\"请确认密码\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  ");

				  	String nickName = "";
				  	if(type == UserType.PersonUser){
				  		nickName = personUser.getNickName();
				  		if(nickName == null){
				  			nickName = "";
				  		}
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>昵名</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(nickName);
      out.write("\" id=\"");
      out.print(ParamUtils.FOREM_USER_NICK_NAME );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_NICK_NAME );
      out.write("\" placeholder=\"请输入昵名\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t  \t  ");
}
      out.write("\r\n");
      out.write("\t\t\t\t  ");

				  String companyName = "";
				  if(type == UserType.CompanyUser){
					  companyName = companyUser.getCompanyName();
				  	if(companyName == null){
				  		companyName = "";
		  			}
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>公司名</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(companyName);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_COMPANY_NAME );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_COMPANY_NAME );
      out.write("\" placeholder=\"请输入公司名\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  ");
}
      out.write("\r\n");
      out.write("\t\t\t\t  ");

				  String realName = "";
				  if(type == UserType.PersonUser){
					  realName = personUser.getRealName();
				  }else if(type == UserType.CompanyUser){
					  realName = companyUser.getRealName();
				  }
				  if(realName == null){
					  realName = "";
					  
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>真实名</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(realName);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_REAL_NAME );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_REAL_NAME );
      out.write("\" placeholder=\"请输入真实名\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  ");

				  String email = "";
				  if(type == UserType.PersonUser){
					  email = personUser.getEmail();
				  }else if(type == UserType.CompanyUser){
					  email = companyUser.getEmail();
				  }
				  if(email == null){
					  email = "";
					  
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>邮箱</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(email);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_EMAIL );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_EMAIL );
      out.write("\" placeholder=\"请输入邮箱\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  ");

				  String qq = "";
				  if(type == UserType.PersonUser){
					  qq = personUser.getQQ();
				  }else if(type == UserType.CompanyUser){
					  qq = companyUser.getQQ();
				  }
				  if(qq == null){
					  qq = "";
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>QQ</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(qq);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_QQ );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_QQ );
      out.write("\" placeholder=\"请输入QQ\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t   ");

				  String tel = "";
				  if(type == UserType.PersonUser){
					  tel = personUser.getTel();
				  }else if(type == UserType.CompanyUser){
					  tel = companyUser.getTel();
				  }
				  if(tel == null){
					  tel = "";
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>电话</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(tel);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_TEL );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_TEL );
      out.write("\" placeholder=\"请输入电话\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  ");

				  String address = "";
				  if(type == UserType.PersonUser){
					  address = personUser.getAddress();
				  }else if(type == UserType.CompanyUser){
					  address = companyUser.getAddress();
				  }
				  if(address == null){
					  address = "";
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>地址</label>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" value=\"");
      out.print(address);
      out.write("\"  id=\"");
      out.print(ParamUtils.FOREM_USER_ADDRESS );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_ADDRESS );
      out.write("\" placeholder=\"请输入地址\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t   ");

				  String intro = "";
				  if(type == UserType.PersonUser){
					  intro = personUser.getIntroduce();
				  }else if(type == UserType.CompanyUser){
					  intro = companyUser.getIntroduce();
				  }
				  if(intro == null){
					  intro = "";
				  }
				  
      out.write("\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <label>简介</label>\r\n");
      out.write("\t\t\t\t    <textarea class=\"form-control\" rows=\"3\" id=\"");
      out.print(ParamUtils.FOREM_USER_INTRO );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_INTRO );
      out.write("\" placeholder=\"请输入简介\" >");
      out.print(intro);
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <button id=\"btn-form-modify\" type=\"submit\" class=\"btn btn-block btn-success btn-lg\">修改</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t");

				switch(type){
				case Visitor:
					out.println("<img width=\"200px\" src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
					break;
				case PersonUser:
					if(personUser != null){
						if(personUser.getAvatar() != null){
							out.println("<img width=\"200px\" src=\""+personUser.getAvatar()+ "\""+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img width=\"200px\" src=\""+request.getContextPath()+ "\""+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				case CompanyUser:
					if(companyUser != null){
						if(companyUser.getAvatar() != null){
							out.println("<img width=\"200px\" src=\""+companyUser.getAvatar()+"\""+" class=\"img-responsive img-rounded\"/>");
						}else{
							out.println("<img width=\"200px\" src=\""+request.getContextPath()+"/images/ct.jpg\" class=\"img-responsive img-rounded\"/>");
						}
					}
					break;
				}
				
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t");

					String avatorUploadPath = request.getContextPath() + ParamUtils.SERVLET_USER_AVATAR; 
					avatorUploadPath += "?" + ParamUtils.FOREM_USER_ID + "=" + id + "&";
					avatorUploadPath += ParamUtils.FOREM_USER_TYPE + "=" + mTpye;
				
      out.write("\r\n");
      out.write("\t\t\t\t<form role=\"form\" method=\"POST\" enctype=\"multipart/form-data\" action=\"");
      out.print(avatorUploadPath);
      out.write("\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <input type=\"file\" id=\"");
      out.print(ParamUtils.FOREM_USER_AVATAR );
      out.write("\" name=\"");
      out.print(ParamUtils.FOREM_USER_AVATAR );
      out.write("\">\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <button type=\"submit\" class=\"btn btn-info btn-block\">上传</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/javascript/index.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
